blank_issues_enabled: false

contact_links:
  - name: HomeSite Discussions
    url: https://github.com/Master3307/HomeSite/discussions
    about: Ask general questions or start non-actionable discussions here.
